services:
  - type: web
    name: invoice-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 300 --workers 2 --threads 2 app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 300 --keep-alive 65"