services:
  - type: web
    name: invoice-extractor
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    plan: free
    autoDeploy: true
